### PR TITLE
Issue#144 shop list mobile

### LINKED ISSUE #114: FEAT: Handle shop list mobile

### PR DESCRIPTION
**Pull request by fajfara**
Shoplist sidebar is now hidden by default on mobile. When you press the shopping basket icon it now opens the shopping list. Also if you swipe left the shopping list opens (we might think of adding some sort of tutorial animation, just some swipe icon going from right to left, so users on mobile know that is how you can get to the shop list faster). I tested swiping on an actual device it seems to work, but I think it requires more QA. This PR closes #114

### CODE REVIEW

**Review by ips-coding-challenge — CHANGES_REQUESTED** [review]
Hi ;). 

Some things that I noticed: 
- The sidebar should close when we click on the navbar
- The sidebar should open when we click on an item

Also, I think we should reduce the height of the "add item block" and the height of the modal at the bottom of the shopList ( to see more items in the shopList )

I also noticed an issue on the Ipad dimension and iphoneX (in landscape mode). Should we show the sidebar only on large screens?

I feel like I'm always "complaining" :D. If you don't have time to re-work on that, feel free to tell me as I can work on those issues if you want ;)

**Comment by fajfara** [comment]
Yeah, no worries, I was planning to the responsive styling in another issue/PR, this was more meant for the showing of the shop list (i guess I wrote the issue wrong, it can be interpreted either way), I will do the responsive styling in this PR.

**Comment by fajfara** [comment]
I must admit, I didn't test this one 100%, let me know if its ok now.

**Review by ips-coding-challenge — CHANGES_REQUESTED** [review]
I think the click on an item should open the sidebar and the click on a navbar should close it.

Aside from that, it works well ;)

**Comment by fajfara** [comment]
I think the click on an item should open the sidebar and the click on a navbar should close it. <- This part should already work 😕 
The long item name I will handle with fixed max-width on mobile, but I am not really sure how to handle item name in edit mode 😕 
Any ideas for that?

**Comment by ips-coding-challenge** [comment]
First of all, I think we should remove a lot of padding on mobile mode which will add some space. Otherwise, I think flexbox should be able to handle pretty much everything in this scenario but maybe I'm wrong :D. I will try to play with this branch to see what I can do :D

**Comment by ips-coding-challenge** [comment]
I've got something which seems to work. Do you want me to push what I did to another branch to check what I did? 
I split what you had into two components instead of one. There is a little repetition but I think it improves readability in that particular case and it's easier to work on the Css.

test_long_name

**Pull request merged**
