### PR TITLE
FEAT: Add button to add a new item on the ItemShowSidebar

### LINKED ISSUE #135: FEAT: Add a "Add a new item" button on the "showItemSidebar"?
When I start to add items, it feels kinda weird to not be able to chain the "add" action. I need to click on the back button to go back to the shopList and then re-click on "add a new item". I wonder if it would not be better to add a new button "add another item" which will simply redirect to the AddItemSidebar?

### PR DESCRIPTION
**Pull request by ips-coding-challenge**
I tried different positions/colors for the button but if you have other ideas, feel free to modify the emplacement/style.

addnew_button

closes #135

### CODE REVIEW

**Comment by fajfara** [comment]
Hm, the button seems kind of out of place there :S 
I think we should figure out a way how to put this button where the delete and add to list are.
Or perhaps we could reuse AddNewItemCTA component here, perhaps put it at the top or bottom.

**Comment by ips-coding-challenge** [comment]
I tried first to put it with the two other buttons but I didn't like it. I think the CTA will be too big when the item will have an image :/.

I'm not sure where to place it. I will give it another try tomorrow to see if I can find a better place.

**Comment by ips-coding-challenge** [comment]
new_btn

Do you think it's better like that?

**Comment by fajfara** [comment]
Hey, it looks nice. I might like it better on the left side, but lets leave it like this for now, we can easily change it later.

**Pull request merged**
