### PR TITLE
Issue#85 refactor editable field

### LINKED ISSUE #85: FEAT: Extract editable title into own component
I will try to use contentEditable for this ...

### PR DESCRIPTION
**Pull request by fajfara**
As far as I tested works ok. I didn't pay too much attention to styling just the functionality, so some styles might be 'broken' :D
Closes #85

### CODE REVIEW

**Review by ips-coding-challenge — COMMENTED** [review]
I'm not convinced at all. The user experience is not great I think. For example, when you want to edit a category, you can't hit enter to save the category anymore. It can create some weird results. For example, adding a new line by mistake will make this result: Beverages<div><br></div>

Also, I don't see what's the problem with a simple input? ;)

**Comment by fajfara** [comment]
If you want to save data when hitting enter, it can be changed to form and use save as a submit button, that fixes the ux and accessibility. Speaking of UX and accessibility, I just noticed that both save and edit are not buttons? I will need to fix that.
This implementation is much cleaner than with inputs (notice no jumping of content, flow items not changing, especially with the shopping list name going into multiple lines)

**Comment by ips-coding-challenge** [comment]
At least, a user shouldn't have the possibility to add a new line when editing category or list title. For accessibility problems, I indeed have to improve a lot in that domain ;). Also, I noticed that the cursor is not visible when trying to put it at the end of the word. So maybe add some padding to see that we are actually editing something ;)

**Comment by fajfara** [comment]
When pressing enter while editing the category title it saves the title, I also left default styles for buttons on category edit looks cool with the slight border created by shadow while hovering.

**Review by ips-coding-challenge — CHANGES_REQUESTED** [review]
Looks ok ;). 

One more thing though. I think the contentEditable should take the focus when we click on edit.

**Pull request merged**
